### ISSUE TITLE
Improvement idea

### ISSUE THREAD

**Issue by iosifnicolae2** [simplecto/django-reference-implementation#66]
Hi there, I'm the founder of django-superapp.

I'm wondering, wouldn't it be useful to structure your project using [django-superapp](https://django-superapp.bringes.io/) and then create independent app templates that can be integrated very quickly by developers into their own projects?

Looking forward to your feedback.

**Comment by undernewmanagement** [comment]
Thank you for the suggestion! I was not familiar with django-superapp until now.

While I appreciate the idea, I don't think we can accommodate this directly in the app. It does give me an idea, however:

Lets open a section in the `readme.md` where we mention (but not endorse) other Django templating projects. We can include django-superapp, cookiecutter, and saasPegasus (paid).

**Comment by iosifnicolae2** [comment]
The main idea behind SuperApp is to quickly set up projects and provide the ability to push changes to each app template for each project (https://django-superapp.bringes.io/apps/push-template-changes).

Anyway, I'm not trying to promote this library, as it was built primarily to solve my own problem. If it is also helpful to others, that's good.
